services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gst_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb+srv://hariom:hariom007@cluster0.qtcwg.mongodb.net/gst_management
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: gst_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
      